// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9yyMMqFAHUnGiO8AgmsuyzEslliFRzQU',
    appId: '1:146569086035:android:0f846f7a5006a010e432a6',
    messagingSenderId: '146569086035',
    projectId: 'micro-health-90016',
    databaseURL: 'https://micro-health-90016-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'micro-health-90016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGl6uq3lkfH2eY_vb5LoepxixgHQJWAx0',
    appId: '1:146569086035:ios:4466d38cadcf63d5e432a6',
    messagingSenderId: '146569086035',
    projectId: 'micro-health-90016',
    databaseURL: 'https://micro-health-90016-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'micro-health-90016.firebasestorage.app',
    iosBundleId: 'com.example.microHealth007',
  );
}
